name: test-github-actions
on: [push]
    
jobs:
  run_actions_test:
    runs-on: ubuntu-latest
    steps:
        - name: Set up R
          uses: r-lib/actions/setup-r@v2
        
        - name: checkout Code
          uses: actions/checkout@v4
        
        - name: run
          run: Rscript -e "source('R/test.R')"
          
        - name: Commit
          run: |
            git config --local user.email "Jprichard314@gmail.com"
            git config --local user.name "Github Actions"
            git add *
            git commit -m "Commit data"
            git push origin
  
  import_data:
    runs-on: ubuntu-latest
    steps:
      - name: build_r
        uses: r-lib/actions/setup-r@v2
      
      - name: checkout_code
        uses: actions/checkout@v4
        with: 
          submodules: true
          
      - name: get_libraries
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::httr
            
      - name: run
        run: Rscript -e "source('R/test2.R')"
        
      - name: Commit
        run: |
          git config --local user.email "Jprichard314@gmail.com"
          git config --local user.name "Github Actions"
          git add *
          git commit -m "Commit data"
          git push origin
