on:
  push:
    branches: master
    
jobs:
  run_actions_test:
    runs-on: ubuntu-latest
      steps:
        - name: Set up R
          uses: r-lib/actions/setup-r@v2
        
        - name: checkout Code
          uses: actions/checkout@v3
        
        - name: run
          uses: Rscript -e "source('R/test.R')"
          
        - name: Commit
          run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"
            git add *
            git commit -m "Commit data"
            git push origin
        